### ISSUE TITLE
why ignore `package-lock.json`?

### ISSUE THREAD

**Issue by alireza-mh** [esamattis/postcss-ts-classnames#1]
I think having `package-lock.json` in the repository is beneficial.
more detail can be found. 
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by esamattis** [comment]
Because this is a library and not an application.

For example this lib depends on postcss `^7.0.21` which means that when the users of this library install it they will get the lastest postcss according to that semver range. It might be `7.0.21` or even `7.99.99`.

It should be still compatible with postcss-ts-classnames but if postcss would accidentally introduce a breaking change and I would have the package-lock.json committed my CI system would not detect that error because the lock file means that the CI will and my local dev env would be still getting `7.0.21` exactly.

I want to know about that situation as soon as possible.

**Comment by alireza-mh** [comment]
Thanks for your detail reply. :)
